.github/PULL_REQUEST_TEMPLATE
chevah_build
functions.sh
python-modules/chevah-python-test/test_python_binary_dist.py
src/gmp/chevahbs
src/libffi/chevahbs
src/python/chevahbs

Scope
=====
Update build system to create package for ubuntu 16.04
Changes
========
Since pyopenssl 0.13 no longer works with OpenSSL available on Ubuntu 16.04  i have updated the build system to the one similar to Arch.
In the future all builds should use that system.
I have refactored a bit the windows part to re-use the common process.
src/python/chevahbs no longer installs pip, but just make sure that we have a minimal python.
I have also enable new build system for rhel 5,6,7 and sles 11,12 and generic linux, raspbian7, openbsd and solaris11
aix, freebsd and solaris10 are broken ... but since solaris 10 has a very old openssl I am not sure if we can upgrade it.
As a drive by I have added the github PR template.
How to test
=========
reviewers: @brunogola @dumol @alibotean 
check that …

[#3418] Build for Ubuntu 16.04 and update Linux, OpenBSD and OSX builds to cffi.

---

README
chevah_build
paver.sh

Scope
=====
This add support for building the python package on SLES 10
Changes
=======
SLES 10 has an old openssl 0.9.8 so we build using the old pyopenssl 0.13.0
libedit is disabled on sles10
reviewers: @dumol 
check that changes are ok.
I have pushed a first version in production and I will test this with compat and chevah.server

[#3468] Add support for SLES 10.

---

src/python/Python-2.7.10/Lib/ctypes/__init__.py

Scope
=====
See 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781578
and
https://bugzilla.redhat.com/show_bug.cgi?id=674369
Changes
=======
I went for executing that code only on Windows... since it a windows only hack.
reviewers: @alibotean 
check that changes make sense.

[#3777] Only do the ctypes windows hack on windows.

---

paver.sh

Scope
=====
On OSX the temporary pip directory was not removed if pip failed as it is not under /tmp.
Changes
=======
Add code to clean the folder under ${TMPDIR}.
reviewers: @adiroiban @dumol 
Please check if changes make sense.

[#3827] Clean temporary directory on OSX.

---

README
chevah_build
python-modules/get-pip-pin.patch

Scope
=====
This updates the build script for python to use a pinned version for pip and setuptools.
In previous code the latest version was used so if the pypi server was update, we would end up with different python distribution, for the same commit
Changes
=======
There is no way for get-pip.py to install a specific pip. it will always install the latest...so I had to patch it.
for setuptools there was a workarround 
reviewers: @dumol 
check that changes make sense
we have newer setuptools in our pypi,chevah.com mirror.
you can try updating the chevah_build with an even older pip version and check that the requiest version is used

[#4024] Use a fixed version of pip and setuptools

---

chevah_build
functions.sh

Scope
=====
`machinfo | grep proc | grep core | awk '{print $1}'` only works as intended on HP-UX machines with a single physical processor.
Changes
=======
After some digging, I found a command that I was able to massage into giving us the **logical** number of CPUs. However, this seems to suit HP-UX hardware, as on Mosna I got slightly better compile times with 4 threads¹ (the number of logical CPUs) compared to 2 threads² (the number of physical CPUs), when compiling `python-package` without GMP.
1. https://chevah.com/buildbot/builders/python-package-hpux-dev/builds/0
2. https://chevah.com/buildbot/builders/python-package-hpux-dev/builds/1
**Drive-by changes**:
* re-discovered a bug with compiling GMP on HP-UX with more than 2 threads. Filled it to be reported upstream on a hacking day …

[#4299] HP-UX processor count fix.

---

paver.conf
paver.sh
python-modules/chevah-python-test/get_binaries_deps.sh
python-modules/chevah-python-test/test_python_binary_dist.py
src/python/chevahbs

Scope
=====
`paver.sh` tries to use a generic Linux package in Alpine, but that fails.
Changes
=======
Identify Alpine Linux.
Check for version 3.6 or newer.
Use `lddtree -l`, as musl's ldd has issues with some Python modules.
Updated deps to accommodate this peculiar little distro.
Mark resulting `python` binary with `paxctl` for EMUTRAMP, otherwise grsec kernels will kill it, as default behaviour violates MPROTECT.
Updated `paver.conf` accordingly.
Run the tests.
Run a server test with latest package, eg. https://chevah.com/buildbot/builders/server-alpine/builds/25

[#4322] Alpine Linux support

---

paver.sh
python-modules/chevah-python-test/test_python_binary_dist.py
src/python/disabled_modules.patch
src/python/readline_libedit.patch

Scope
=====
Ubuntu detection in `paver.sh` fails if `lsb-release` package missing. Detected on Pine64 after removing `python3*` packages.
Changes
=======
Refactored Ubuntu detection to use `/etc/os-release`, present in Ubuntu 14.04 and newer, the only releases currently supported.
When older supported Linux distros (without `/etc/os-release`) are phased out (RHEL 6 and SLES 10&11), we could move to using `/etc/os-release` exclusively for distro detection in Linux (except for Arch, which is a rolling release distro and thus has no version info in that file).. 
**Drive-by changes**:
* use `/etc/os-release` for Raspbian and Alpine Linux too
* never build the `_locale` Python module to avoid depending on `libintl`, the GNU gettext libs
* updated AIX deps with full paths after installing …

[#4318] Detect Ubuntu without LBS tools.

---

chevah_build
python-modules/chevah-python-test/test_python_binary_dist.py

Scope
=====
With latest production Python packages, some of the packages use a git rev of 7 characters and others use 8 characters. This leads to broken tests, as the used length is not consistent among similar build slaves (being dependent of `core.abbrev` conf variable according to `git-rev-parse(1)`).
Changes
=======
Force the length of 8 for consistency.
Test the length of the git rev set in the binary.
**Drive-by change**:
* really minor comment clarification in regards to `sqlite` libs to link to in Solaris 10.
Run the automated tests, eg: https://chevah.com/buildbot/builders/python-package-gk-review/builds/39

[#4425] Use a fixed length for the git rev in the version.

---

paver.sh

Scope
=====
`VERSION_ID` is sometimes missing from `/etc/os-release`.  For example on my old Gentoo installation that I keep around at home. Result:
```
$ ./paver.sh
./paver.sh: line 603: VERSION_ID: unbound variable
```
Also, Ubuntu non-LTS versions are now rejected, while we used to equate them with generic Linux before introducing support for `/etc/os-release`.
Changes
=======
Only use `VERSION_ID` from `/etc/os-release` on supported distros, for now: Ubuntu, Raspbian and Alpine. This variable is not set on some rolling-release distros according to https://www.freedesktop.org/software/systemd/man/os-release.html.
Use generic Linux binaries on non-LTS Ubuntu versions.
reviewers: @adiroiban
Run …

[#4437] Minor /etc/os-release fixes.

---

chevah_build
python-modules/chevah-python-test/test_python_binary_dist.py

Scope
=====
It looks like sqlite is no longer working on solaris 10 sparc.
Changes
=======
Use a test that actually breaks when `pysqlite2` module is broken.
Link to `sqlite` libs in `/usr/lib/mps` only on Solaris 10 versions up to u7.
Output the version of both SQLite system lib and the corresponding Python module.
Run the automated tests, eg. https://chevah.com/buildbot/builders/python-package-group-all/builds/4

[#4483] Functional pysqlite2 module on Solaris 10 SPARC.

---

paver.conf
paver.sh

Scope
=====
Now that we don't use VERSION_ID for all distros where we count on `/etc/os-release`, Arch as rolling-release distro should fit among them as well.
Changes
=======
Stop using `/etc/arch-release` in favour of `/etc/os-release`.
**Drive-by change**:
* updated `paver.conf`
Check that Arch is detected properly by `paver.sh`.

[#4438] Use /etc/os-release for Arch Linux too.

---

python-modules/chevah-python-test/test_python_binary_dist.py

Scope
=====
Local Python tests check for full deps in all OS'es except Linux. Enable this for supported distributions.
Changes
=======
Rebuilt list of deps for supported Linux distro to include full paths.
Change the way we parse `ldd`'s output to make this possible in Linux distros other than Alpine (which already had it enabled).

[#2696] Full deps check for all supported Linux distributions.

---

.gitignore
chevah_build
src/gmp/chevahbs

Scope
=====
Parallel builds of GMP fail on HP-UX when using more than 2 threads… Eg. https://chevah.com/buildbot/builders/python-package-hpux-dev/builds/3/steps/build/logs/stdio:
```
Making target"mpn/mp_bases.lo"
/bin/sh ./libtool  --tag=CC    --mode=compile /opt/aCC/bin/cc -w -DHAVE_CONFIG_H  -I.  -D__GMP_WITHIN_GMP    +O2 -c -o mpn/mp_bases.lo mpn/mp_bases.c
libtool: compile:  /opt/aCC/bin/cc -w -DHAVE_CONFIG_H -I. -D__GMP_WITHIN_GMP +O2 -c mpn/mp_bases.c -o mpn/mp_bases.o
Making target"config.h"
At end of source: error #2018: expected a ")"
"mpn/mp_bases.c", line 185: error #2274: improperly terminated macro invocation
/* 173 */ { 8, CNST_LIMB(0x226ef7776aa7fd29), CNST_LIMB(0x
^
At end of source: error #2029: expected an expression
At end of source: error #2067: expected a "}"
At end …
```

[#4308] Limit parallel builds on HP-UX for GMP only.

---

chevah_build
paver.conf
paver.sh
python-modules/chevah-python-test/test_python_binary_dist.py

Scope
=====
As discussed in #4092, remove code that automatically installs/uninstalls packages for building `python-package` and just make sure the dependencies of `chevah_build.sh` are documented. Also, relevant and helpful errors should be generated when needed binaries/libs are missing.
Changes
=======
Remove code that uninstalled packages.
Updated code that installed packages to only check for required packages.
Quit with a relevant error when one or more packages are missing, eg. https://chevah.com/buildbot/builders/python-package-sles-11/builds/6/steps/build/logs/stdio.
**Drive-by fixes**:
* updated `paver.conf` and `paver.sh` from `server` repo
* consequently, updated minimum supported RHEL version to major version 5
* make it possible to use a symbolic link for `build/` …

[#4712] No more package management at build time.

---

python-modules/chevah-python-test/test_python_binary_dist.py
src/python/chevahbs

Scope
=====
Update Python packages for OS'es with OpenSSL 1.0.1 for which we use older versions.
Changes
=======
Python 2.7.14 builds with no issues on RHEL 7.3 with OpenSSL 1.0.1. The lib deps tests needed a minor fix.
Couldn't build Python 2.7.14 on AIX 7.1 with OpenSSL 1.0.1e (there are several releases from IBM with this version, nothing worked for me). The issues are documented in the associated Trac ticket: https://trac.chevah.com/ticket/4797#comment:3.
This means on AIX we should keep using 2.7.13 until both clients stuck on the unsupported 1.0.1 version of OpenSSL upgrade to 1.0.2k.
**Drive-by change:**
* stop disabling IPv6 support on HP-UX as it doesn't break the build any more with 2.7.14. 
reviewers: @adiroiban …

[#4797] Updated packages for RHEL7 with OpenSSL 1.0.1 and HP-UX.

---

chevah_build
python-modules/chevah-python-test/test_python_binary_dist.py

Scope
=====
Our bundled `libffi` is used twice:
1. by Python if using `--with-system-ffi` (on AIX and HP-UX)
2. by CFFI (on all platforms where we use pip/cffi/cryptography).
Stop building `libffi` unnecessarily on OS'es which bundle and support it. Linking to OS-provided `libffi` means one less liability from a security point of view.
Changes
=======
Build CFFI against OS libs where this is possible (everywhere but AIX and HP-UX).
But also on the BSDs, where `libffi` is not included in the base system and has to be installed as a package. I'm ambivalent about this one though, as you can see from the history of changes.
Systems not building CFFI are not affected (currently Windows and Solaris 10).
Systems not tested, but for which I deduced required deps: Solaris 11 SPARC 64bit (as we …

[#4833] Build libffi only when needed.

---

chevah_build
paver.conf
src/gmp/chevahbs
src/libffi/chevahbs
src/python/chevahbs

Scope
=====
HP-UX python-package builds sometimes fail on Mosna.
Initially, this seems to be related to Mosna specifically, but further testing focused on this specific issue revealed the root cause for this to be parallel building, especially for GMP, but sometimes for Python as well.
Changes
=======
Use `gmake` for GMP and Python on HP-UX. This means no parallel builds for these two components on HP-UX.
Switch back to using the regular C compiler on HP-UX, instead of the C++ compiler in _C mode_. This was only necessary for building GMP with more than 2 threads.
**Drive-by change**:
* updated `paver.conf` with latest stuff.
Run the tests. You'll have to do 10 in a row to make …

[#4205] HP-UX build fixes.

---

chevah_build

Scope
=====
Following the work in Trac ticket #4712, we don't install/uninstall packages anymore when building Python, but we check for required packages on some of the systems.
We could add Alpine to that list of systems.
Changes
=======
Check required packages in Alpine with `apk` (and in Arch Linux with `pacman` while at it).
Check that essential commands are present on OS'es where we don't check for installed packages: Windows, the Unices, OSX/macOS, the BSDs and generic Linux.
**Drive-by changes**:
* also check for `git` and `patch` everywhere as they are actually required
* fixed a bug that prevented package verification on SLES 11 in last revisions
* various related minor fixes: comments, outputs, code syntax. …

[#4773] Package verification for all Linux distros, check essential commands everywhere else.

---

chevah_build
paver.sh
python-modules/chevah-python-test/test_python_binary_dist.py

Scope
=====
Support for Amazon Linux 2.  Using ​https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html.
Changes
=======
Recognize `amzn` Linux distribution type.
Support Amazon Linux version 2 and newer.
**Drive-by fix**:
* nicer exit message for unsupported Linux distros with `/etc/os-release` files.
Please review the simple changes.
Manually test on one of the new `amazon` slaves on Fiser and Ghindari, not yet integrated in our Buildbot setup. All tests pass with no changes other than the dep checks.

[#5124] Amazon Linux support.

---

chevah_build
functions.sh
paver.conf

Scope
=====
There's not much left until 2019-05-01, the end of support date for Alpine Linux 3.6, according to ​https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases.
While at it, see what's with the `no_aes` Alpine slaves, which seem completely unused, wasting RAM.
Changes
=======
`salt-master` fixes were done as a drive-by in https://github.com/chevah/salt-master/pull/413.
I left the Alpine 3.6 slave alone for now.
Updated the `no_aes` Alpiine slave on Lotu to 3.7. There seem to be less persistent issues now when testing server: https://chevah.com/buildbot/builders/server-alpine-37/builds/3/steps/test/logs/stdio
For the other `no_aes` Alpine slave on Neaua I chose to reinstall with the _Standard_ install disk, not the _Virtual_ one. There seem to be one less persistent issue here: …

[#5168] Alpine 3.7 support.

---

chevah_build
python-modules/chevah-python-test/test_python_binary_dist.py

Scope
=====
Adding `psutil` support.
Changes
=======
Build `psutil` everywhere except:
* Windows, where we use the upstream wheel
* HP-UX, for which there is no support from uppstream
* AIX 5.3, where the build fails.
**Drive-by fixes**:
* updated deps for Alpine 3.7 and Debian 8
* build Debian packages as portable as possible, there might be of some use on other unsupported Linux platforms. This means no `readline` module on Debian.

[#5180] Build psutil on supported platforms.

---

chevah_build
python-modules/chevah-python-test/test_python_binary_dist.py

Scope
=====
Fix HP-UX build, the work in #132 broke it a couple of ways.
While at it, update cryptography to 2.7 for CVE-2019-1543, fixed in OpenSSL 1.1.1c.
Changes
=======
Fixed HP-UX build to not build or test `bcrypt` package.
Updated `cryptography` to latest stable version, 2.7.
Uploaded 2.7 `cryptography` source package and wheels for Windows / OS X / SLES 11 on binary server.
reviewers:  @adiroiban 
Run the automated tests. For ALL slaves. :-]

[#5286] Cryptography 2.7 update. HP-UX fixes.

---

chevah_build
functions.sh

Scope
=====
Fixes #154.
Fixes #155.
Changes
=======
Only use an HTTP PyPI server on AIX for `cryptography`'s deps. The previous check was wrong because it checked `$OS` before it was defined.
Use the `ld` hack when building Safety deps AIX, otherwise installing Cython as a dep for PyYAML fails on AIX, where it has to be built.
**Drive-by fix**:
* Enabled basic Bash checks to avoid issues with empty env vars in the future.

Minor AIX-related fixes.

---

.github/workflows/docker.yaml
brink.sh
chevah_build
external_deps.csv
external_deps.fods
functions.sh
pavement.py
python-modules/chevah-python-test/test_python_binary_dist.py
src/openssl/chevahbs

Scope
=====
Build an Ubuntu 22.04 package.
Changes
=======
The latest cryptography version to support Python 2.7 is 3.3.2, and that has no support for OpenSSL 3.0.x.
Therefore, use the generic Linux package on Ubuntu 22.04 for now.
For the record, `cryptography` **3.4.x** has been patched to support that for Python 3 though, e.g. https://814773.bugs.gentoo.org/attachment.cgi?id=743943.
**Drive-by fixes**:
* Backported minor improvement from `pythia` repo: pypi args, pkg mgmt, openssl manual installation, more error checks.
* Updated documented external dependencies.

Ubuntu 22.04 support.
